spring:
  main:
    banner-mode: off
  application:
    name: gdal-benchmark

benchmark:
  compressions: deflate, lzw, zstd, jxl
  files:
    - data
  result-path: results
  tmp-file-path: tmp
  extensions: tif, tiff