name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3

      - uses: docker/setup-buildx-action@v2

      - run: |
          ./gradlew buildMultiArchImage \
            -Pimage.registry.publish.username=${{github.actor}} \
            -Pimage.registry.publish.password=${{secrets.GITHUB_TOKEN}} \
            -Pimage.publish=true

